### ISSUE TITLE
Strange line in code of Account#to_response_object

### ISSUE THREAD

**Issue by petRUShka** [nov/openid_connect_sample#15]
There is a [line](https://github.com/nov/openid_connect_sample/blob/master/app/models/account.rb#L26) in `Account.rb`:

    PairwisePseudonymousIdentifier.find_or_create_by_sector_identifier(access_token.client.sector_identifier).identifier

It finds or **creates** `PairwisePseudonymousIdentifier` which has [validation](https://github.com/nov/openid_connect_sample/blob/master/app/models/pairwise_pseudonymous_identifier.rb#L7) on presence of `account`. So it is impossible to create `PairwisePseudonymousIdentifier` that way.

My question is following. What should be done:

1. `find_or_create_by_sector_identifier` be replaced by `find_by_sector_identifier`,
2. or `find_or_create_by_sector_identifier(access_token.client.sector_identifier)` be replaced by `self.pairwise_pseudonymous_identifiers.find_or_create_by_sector_identifier`?

**Comment by sai43** [comment]
I am registered app with facebook but when i am trying to login with facebook it shows "Facebook cookie not found" exception. i am also set the client_id, client_secret, scope as per my requirement but no use.
