### ISSUE TITLE
Google signin no longer discovering

### ISSUE THREAD

**Issue by jpete7683** [nov/openid_connect_sample#16]
Is there any valid reason why the OP can no longer discover .well-known/openid-configuration on the accounts.google.com?

**Comment by jpete7683** [comment]
We are receiving a 404 error

With the line @config.merge! OpenIDConnect::Discovery::Provider::Config.discover! is where it is bombing out with the 404.
              
        @config = YAML.load_file("#{Rails.root}/config/connect/google.yml")[Rails.env].symbolize_keys
        @config.merge! OpenIDConnect::Discovery::Provider::Config.discover!(
          @config[:issuer]
        ).as_json
        if Rails.env.production?

**Comment by nov** [comment]
I guess it's just a temporary outage on Google side.
